name: Build project into IPA
on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions a tab
  workflow_dispatch:

jobs:
  deploy:
    name: Build project into IPA
    runs-on: macOS-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Deploy iOS to Firebase via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: build_ipa_to_firebase
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_CLI_TOKEN }}'
          FIREBASE_APP_ID: '${{ secrets.FIREBASE_APP_ID }}'
          DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
          DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'